<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vijay-Vidja" failures="1" tests="3" name="Test" time="23.451" errors="0" timestamp="2023-02-12T13:07:47 IST">
  <testcase classname="com.vijaytest.logintest" name="login_test" time="23.39"/>
  <testcase classname="com.vijaytest.appTest" name="testlogin1" time="0.007"/>
  <testcase classname="com.vijaytest.appTest" name="testlogin2" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at com.vijaytest.appTest.testlogin2(appTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testlogin2 -->
</testsuite> <!-- Test -->
